### ISSUE TITLE
Thank you for sharing your theme!

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [millsp/material-candy#1]
Very impressed your work! can i request Jupyter mode in vscode? it seems not work there.

Thank you very much! i will keep it till you update it!

**Comment by millsp** [comment]
Hey @JUNGHUNKIM-7 can you send a piece of code for me to do the repro. An what are your expectations, colors, etc? Or link me an example repo with some examples? I'm not familiar with Jupyter or Python. Thanks!

Glad you love the theme :+1:
