### ISSUE TITLE
Emacs port?

### ISSUE THREAD

**Issue by shaneikennedy** [millsp/material-candy#2]
## 🤔 Question
👋 Thanks for this theme, I really like it! Would you mind if I submitted an emacs port of this and submitted it to the emacs package manager? Here's the [repo](https://github.com/shaneikennedy/emacs-material-candy), it's not 100% identical but I tried my best 😅

**Comment by millsp** [comment]
No problem!

**Comment by shaneikennedy** [comment]
Thanks!
