### ISSUE TITLE
Installation Questions

### ISSUE THREAD

**Issue by namey9089** [millsp/material-candy#4]
## 🤔 Question
Hello, I was wondering how to install materal-dynmap server side. According to the website, I need to find dynmaps location context. Where can I find it?
#### Describe your question

I wish to know where I can find the location context.
#### Search tags, topics

#installation #install

**Comment by ghost** [comment]
There is a JAR file available now, it may be easier to use that:

> https://dev.bukkit.org/projects/materialdynmap/files

Sorry for the incorrect link. Issues go at https://github.com/SNDST00M/material-dynmap for Material Dynmap

**Comment by ghost** [comment]
@millsp please close this issue
